--- # This playbook installs ansible
- hosts: webservers[1]
  user: ansible
  become: yes
  vars:
    epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
    epel_repo_gpg_key_url: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7"
    pkgs:
      - git
      - python
      - python-pip
      - python-devel
      - openssl
      - ansible
  tasks:
    - name: 2.Install EPEL repo.
      yum:
         name: "{{ epel_repo_url }}"
         state: present
      register: result
    - name: 3.Import EPEL GPG key.
      rpm_key:
          key: "{{ epel_repo_gpg_key_url }}"
          state: present
    - name: install packages
      yum: name={{ pkgs }} state=installed




