--- # Install nginx
- hosts: webservers[1]
  user: ansible
  become: yes
  tasks:
    - name: Installs nginx web server
      yum: pkg=nginx state=present update_cache=true
      notify:
        - start nginx
  handlers:
    - name: start nginx
      service: name=nginx state=started
