- name: installing http package
  yum: pkg=httpd state=latest
- name: "Install Apache Web Server on RHEL Based Systems"
  yum: name=httpd state=latest
  when: ansible_facts['os_family']|lower == "redhat"
- name: "Install Apache Web Server on Debian Based Systems"
  apt: name=apache2 update_cache=yes state=latest
  when: ansible_facts['os_family']|lower == "debian"
- name: "Start the Apache Web Server"
  service:
          name: httpd
          state: started
          enabled: yes
- name: "Enable mod_rewrite module"
  apache2_module:
          name: rewrite
          state: present
  notify:
          - restart apache
